<a href="https://colab.research.google.com/github/wldopie/ESAA/blob/main/HW_220311.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **03. 넘파이(NumPy)**
- 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
- 루프를 사용하지 않고 `대량 데이터의 배열 연산`을 가능하게 하므로, `빠른 배열 연산 속도`를 보장
- 넘파이의 기본 방식을 이해하는 것은 다른 `데이터 핸들링 패키지(ex. 판다스)를 이해하는 데 용이`
---

### **1) 넘파이 ndarray 개요**
- 넘파이 **`array()`**함수는 파이썬의 리스트와 같은 다양한 인자를 입력 받아서 ndarray로 변환하는 기능을 수행
- ndarray 배열의 **`shape`** 변수를 통해 ndarray 배열의 차원을 확인
- **`ndarray.ndim`** : array의 차원을 확인
- 데이터 값이 동일하더라도, 각 데이터들의 차원은 다를 수 있으므로 그 차이를 이해하는 것이 매우 중요

In [2]:
import numpy as np

In [4]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [5]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


---

### **2) ndarray의 데이터 타입**
- `숫자형(int, float, complex)`, `문자형`, `bool` 모두 가능
- **`ndarray.dtype`** : 데이터 타입 확인
- 단, ndarray의 데이터 타입은 연산의 특성상 `같은 데이터 타입`만 가능
- `다른 데이터 유형`이 섞여 있는 리스트를 ndarray로 변환할 경우, `크기가 더 큰 데이터 타입`으로 일괄적인 `형변환`
- **`ndarray.astype()`** : 데이터 타입 변경 

In [7]:
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [8]:
# int형과 string형이 섞여 있는 리스트 -> ndarray로 변경 : 유니코드(string)로 일괄적인 형변환
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

# int형과 float형이 섞여 있는 리스트 -> ndarray로 변경 : float로 일괄적인 형변환
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [9]:
# int32 -> float64로 형변환
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

# float64 -> int32로 다시 형변환
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


---

### **3) ndarray를 편리하게 생성하기 - arange, zeros, ones**
- 특정 크기와 차원을 가진 ndarray를 연속값이나 0, 1 등으로 초기화해 쉽게 생성하기 위함
- 주로 테스트용으로 데이터를 만들거나, 대규모의 데이터를 일괄적으로 초기화할 때 사용
- **`arange()`** : 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환하는 함수
  - arange(start, stop) : start부터 (stop-1)까지의 값을 출력
- **`zeros()`** : shape 값을 입력, 모든 값이 0인 ndarray를 반환하는 함수
- **`ones()`** : shape 값을 입력, 모든 값이 1인 ndarray를 반환하는 함수

In [12]:
# arange
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [13]:
# zeros
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

# ones
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


---

### **4) ndarray의 차원과 크기를 변경하는 reshape()**
- **`reshape()`** : ndarray를 특정 차원 및 크기로 변환하는 함수
- `-1을 인자로 사용`하면 원래 ndarray와 `호환되는 새로운 shape`로 변환
  - row = -1, col = 5 --> `고정된 5개의 칼럼`에 맞는 로우를 자동으로 새롭게 생성
  - row = 5, col = -1 --> `고정된 5개의 로우`에 맞는 칼럼을 자동으로 새롭게 생성
- **`reshape(-1,1)`** : 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환

In [15]:
 array1 = np.arange(10)
 print('array1:\n', array1)     # 1D

 array2 = array1.reshape(2,5)
 print('array2:\n', array2)     # 2D

 array3 = array1.reshape(5,2)
 print('array3:\n', array3)     # 2D

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [16]:
array1.reshape(4,3)

ValueError: ignored

In [19]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)     # 고정된 5개의 칼럼에 맞는 로우를 자동 생성
print('array2 shape:', array2.shape)

array3 = array1.reshape(5,-1)     # 고정된 5개의 로우에 맞는 칼럼을 자동 생성
print('array3.shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3.shape: (5, 2)


In [18]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: ignored

In [21]:
array1 = np.arange(8)
array3d = array1.reshape(2,2,2)
print('array3d:\n', array3d.tolist())     # tolist() : ndarray를 리스트로 변환

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)            # reshape(-1,1) : 2차원이고, 고정된 칼럼이 1인 로우를 자동으로 지정
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


---

### **5) 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)**
- `단일 값` 추출 : `원하는 위치의 인덱스` 값을 지정, 해당 위치의 데이터가 반환
  - 인덱스는 `0부터 시작`
  - 인덱스에 `마이너스 기호`를 사용하면 `맨 뒤에서부터 데이터를 출력`
  - ndarray 내의 데이터값 수정 가능 
  - axis=0 : 로우 방향의 축, axis=1 : 칼럼 방향의 축
- `슬라이싱(Slicing)` : `연속된 상의 ndarray`를 추출하는 방식
  - ndarray[1:5] --> 인덱스 1부터 인덱스 4까지에 해당하는 ndarray를 반환
  - ndarray[:5] --> 처음부터 4까지 출력
  - ndarray[2:] --> 2부터 끝가지 출력
  - ndarray[:] --> 처음부터 끝까지 출력
- `팬시 인덱싱(Fancy Indexing)` : `인덱싱 집합을 리스트 또는 ndarray 형태로 지정`, 해당 위치에 있는 데이터의 ndarray를 반환
- `불린 인덱싱(Boolean Indexing)` : True/False 값 인덱싱 집합을 기반으로, `True에 해당하는` 인덱스 위치에 있는 데이터의 ndarray를 반환
  - `조건 필터링`과 검색을 동시에 할 수 있어 매우 자주 사용되는 인덱싱 방식
  - 불린 인덱싱이 동작하는 단계
    - ndarray의 `필터링 조건`을 [ ]안에 기재
    - `True 값`에 해당하는 `인덱스값만 저장`
    - 저장된 인덱스 데이터 세트로 ndarray 조회

In [22]:
# 1. 단일 값 추출
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(1,10)
print('array1:', array1)

# index는 0부터 시작하므로, array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [23]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [24]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [25]:
# 2차원 ndarray에서 데이터 추출
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [26]:
# 2. 슬라이싱
array1 = np.arange(1,10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [27]:
array1 = np.arange(1,10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [29]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [31]:
print(array2d[0])   # axis = 0 생략 : 로우 축을 기준
print(array2d[1])   # axis = 0 생략 : 로우 축을 기준
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [34]:
# 3. 팬시 인덱싱
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1],0:2] =>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


In [35]:
# 4. 불린 인덱싱
array1d = np.arange(1,10)

# []안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과값:', array3)

array1d > 5 불린 인덱싱 결과값: [6 7 8 9]


In [36]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [37]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [38]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


---

### **6) 행렬의 정렬 - sort()와 argsort()**
- 행렬 정렬 : **`np.sort()`**, **`ndarray.sort()`**
  - `np.sort()` : `원 행렬은 그대로 유지`, 원 행렬의 정렬된 행렬을 반환
  - `ndarray.sort()` : `원 행렬 자체를 정렬`한 형태로 변환, 반환 값은 None
  - `내림차순` 정렬 : np.sort( )`[::-1]` 또는 ndarray.sort( )`[::-1]`
  - 2차원 이상인 경우, axis 축 값 설정을 통해 정렬을 수행
    - `axis=0` : 로우 방향으로 정렬 (`상하 셔플`)
    - `axis=1` : 칼럼 방향으로 정렬 (`좌우 셔플`)
- 정렬된 행렬의 인덱스 반환 : **`np.argsort()`**
  - `np.argsort()` : 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환


In [40]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [41]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [43]:
array2d = np.array([[8,12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)        # 상하 정렬 

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)        # 좌우 정렬

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [44]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [45]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [48]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


---

### **7) 선형대수 연산 - 행렬 내적과 전치 행렬 구하기**
- **`행렬 내적`**(행렬 곱) : **`np.dot()`**
- **`전치 행렬`** : **`np.transpose()`**
  - 원 행렬에서 행과 열의 위치를 교환한 원소로 구성한 행렬

In [50]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [51]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
