<a href="https://colab.research.google.com/github/wldopie/ESAA/blob/main/Session_220314_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

ERROR:root:File `'initialise.py'` not found.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [53]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
a.itemsize      # itemsize : memory size를 확인할 수 있는 명령어

8

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
import numpy; numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
a = np.zeros(10)
a[4]=1      # 5번째 값이므로, index=4
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. **`Reverse`** a vector (first element becomes last) (★☆☆)

In [11]:
a = a[::-1]     # [::-1] : 벡터를 역으로 정렬하는 명령어
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
mat = np.arange(9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [14]:
a = np.nonzero( [1,2,0,0,4,0] )     # np.nonzero() : ndarray에서 0이 아닌 원소들의 index를 출력하는 함수
print(a)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [18]:
a = np.identity(3)     # np.identity(n) = np.eye(n) = n x n identity matrix를 출력하는 함수
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [19]:
a = np.random.random((3,3,3))     # np.random.random((a,b,...)) : random value를 (a,b,...) shape의 matrix로 출력하는 함수   
print(a)

[[[0.09284427 0.21695242 0.51544489]
  [0.17306379 0.71970386 0.23994049]
  [0.19294289 0.74900135 0.38209506]]

 [[0.55737976 0.3134969  0.3375517 ]
  [0.09128051 0.19974759 0.34907475]
  [0.28679133 0.84762989 0.70637576]]

 [[0.85257878 0.81243297 0.48177178]
  [0.42009343 0.99719946 0.42022242]
  [0.41731762 0.00784774 0.58377086]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [25]:
a = np.random.random((10,10))
print(a,'\n')
print('maximum value :', a.max())
print('minimum value : ', a.min())

[[0.38164844 0.8660819  0.47912462 0.45240135 0.4039402  0.35529963
  0.33869517 0.20881891 0.71365421 0.28706579]
 [0.45259975 0.06409073 0.14734166 0.93474348 0.56026581 0.17233854
  0.67019709 0.39348823 0.55670891 0.93470392]
 [0.73061021 0.61220261 0.73867196 0.25653123 0.38046933 0.20625246
  0.04575014 0.75721646 0.67668117 0.25313473]
 [0.60871655 0.82143073 0.08966268 0.64459538 0.03981744 0.54603613
  0.58985826 0.58341263 0.84937173 0.94237652]
 [0.74948172 0.51251003 0.42465674 0.19434961 0.02103929 0.47557932
  0.48772781 0.49318828 0.57037421 0.79781862]
 [0.64996864 0.98912572 0.85408013 0.44838567 0.9689923  0.48867912
  0.28791662 0.31152902 0.25701455 0.25625519]
 [0.58083034 0.31113199 0.09770913 0.82980048 0.45978132 0.32634776
  0.16654254 0.69584735 0.81756547 0.98476738]
 [0.88411937 0.27974053 0.86488118 0.14053729 0.46981501 0.3397268
  0.3058439  0.69787155 0.04974407 0.72324539]
 [0.96072925 0.49534465 0.30928641 0.11139152 0.6512856  0.0877764
  0.01402105 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [29]:
a = np.random.random(30)
print(a, '\n')
print('mean of a :', np.mean(a))     # np.mean() : 평균을 출력하는 함수

[0.52246238 0.441498   0.36367383 0.01767438 0.30423377 0.49893101
 0.73215808 0.69919018 0.97423683 0.46466368 0.20469756 0.12779946
 0.78530867 0.72087709 0.60558745 0.48901498 0.39655726 0.96560388
 0.54564871 0.30006276 0.42573385 0.66109817 0.13642151 0.95529111
 0.38382522 0.37093995 0.14218113 0.69402949 0.90268944 0.85149129] 

mean of a : 0.5227860377111107


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [34]:
def array(a,b):       # 일반화하기 위해 함수로 정의
  x = np.ones((a,b))
  x[1:-1,1:-1] = 0
  return x

print(array(11,8))

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to **add a border** (filled with 0's) around an existing array? (★☆☆)

In [50]:
np.random.random_integers(12)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 12 + 1) instead
  """Entry point for launching an IPython kernel.


6

In [55]:
def border_inside(a,b):     # 일반화하기 위해 함수로 정의
  array = np.ones((a,b))
  array[2:a-1,2:b-1] = 2
  array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
  return array

border_inside(5,7)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 2., 2., 2., 2., 1., 0.],
       [0., 1., 1., 2., 2., 2., 2., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [56]:
# nan
# False
# False
# nan
# True
# False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [59]:
a = np.array([1,2,3,4])
mat = np.diag(a, k=-1)      # np.diag(array, k=0) : k값에 따라 대각선 / 대각선 위 / 대각선 아래에 array가 위치할 수 있도록 하는 함수
print(mat)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [60]:
a = np.zeros((8,8))
a[1::2,::2]=1       # 홀수번째 row --> [0 1 0 1 0 1 0 1]이 출력되도록 설정
a[::2,1::2]=1       # 짝수번째 row --> [1 0 1 0 1 0 1 0]이 출력되도록 설정
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [66]:
help(np.unravel_index)

Help on function unravel_index in module numpy:

unravel_index(...)
    unravel_index(indices, shape, order='C')
    
    Converts a flat index or array of flat indices into a tuple
    of coordinate arrays.
    
    Parameters
    ----------
    indices : array_like
        An integer array whose elements are indices into the flattened
        version of an array of dimensions ``shape``. Before version 1.6.0,
        this function accepted just one index value.
    shape : tuple of ints
        The shape of the array to use for unraveling ``indices``.
    
        .. versionchanged:: 1.16.0
            Renamed from ``dims`` to ``shape``.
    
    order : {'C', 'F'}, optional
        Determines whether the indices should be viewed as indexing in
        row-major (C-style) or column-major (Fortran-style) order.
    
        .. versionadded:: 1.6.0
    
    Returns
    -------
    unraveled_coords : tuple of ndarray
        Each array in the tuple has the same shape as the ``indices``
 

In [61]:
a = np.unravel_index(100,(6,7,8))
print(a)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [64]:
help(np.tile)

Help on function tile in module numpy:

tile(A, reps)
    Construct an array by repeating A the number of times given by reps.
    
    If `reps` has length ``d``, the result will have dimension of
    ``max(d, A.ndim)``.
    
    If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
    axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
    or shape (1, 1, 3) for 3-D replication. If this is not the desired
    behavior, promote `A` to d-dimensions manually before calling this
    function.
    
    If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
    Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
    (1, 1, 2, 2).
    
    Note : Although tile may be used for broadcasting, it is strongly
    recommended to use numpy's broadcasting operations and functions.
    
    Parameters
    ----------
    A : array_like
        The input array.
    reps : array_like
        The number of repetitions of `A`

In [62]:
print(np.tile([[0,1],[1,0]],(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [65]:
a = np.random.random((5,5))
a = (a-np.mean(a))/(np.std(a))      # Normalization
print(a)

[[ 1.33585144  0.09897106  0.24085344 -0.80180134 -1.29514655]
 [ 1.46137561  0.86202045 -1.22183607 -1.147908   -0.51894772]
 [ 1.52943144  1.32464992 -0.03895847 -0.83758955  1.32316818]
 [-1.44382859 -0.56201422  0.14454342  1.55529335 -0.74991044]
 [ 0.17086648 -0.88915547  0.82185055 -0.18290876 -1.17887017]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [67]:
color = np.dtype([("r",np.ubyte),("g",np.ubyte),("b",np.ubyte),("a",np.ubyte)])     # np.dtype() : Datatype을 customizing하는 함수
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [69]:
a = np.random.random((5,3))
b = np.random.random((3,2))
print(np.dot(a,b))      # result = 5x2 matrix

[[1.28308795 0.55700137]
 [1.89152804 0.88767501]
 [0.89806598 0.43405281]
 [0.56495234 0.28255006]
 [0.97007563 0.41966713]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [71]:
a = np.arange(20)
a[(a > 3) & (a < 8)] *= -1      # 3과 8 사이에 있는 숫자들을 모두 음수화하도록 boolean indexing.
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15 16 17 18 19]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [72]:
# 9
# 10
# 일반 sum함수는 -1이 연산에 포함되는데, np.sum함수는 -1이 연산에 포함되지 않고 이니셜포인트 역할을 한다.

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [85]:
Z = np.random.randint(20)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)      # value error

# Z<Z>Z : illegal, 나머지는 legal

1
0
False
0j
0.0
False


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [86]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

# nan
# 0
# [-9.22337204e+18]

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [94]:
a = np.random.random((10))
print(np.round(a))      # np.round(array, decimals=1) : array를 반올림하는 함수

[0. 0. 0. 0. 0. 0. 1. 0. 0. 1.]


#### 30. How to find **`common values`** between two arrays? (★☆☆)

In [95]:
a = np.arange(10)
b = np.arange(20)
intersect = np.intersect1d(a,b)
print(intersect)

[0 1 2 3 4 5 6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [96]:
defaults = np.seterr(all="ignore")
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [97]:
np.sqrt(-1) == np.emath.sqrt(-1)

# False

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [105]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1)
tomorrow = today + np.timedelta64(1)

print(yesterday)
print(today)
print(tomorrow)

2022-03-13
2022-03-14
2022-03-15
