<a href="https://colab.research.google.com/github/wldopie/ESAA/blob/main/HW_220314.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [9]:
A = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(A)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [41]:
A = np.random.random((2,2))
B = np.random.random((2,2))

result = np.dot((A+B), (-A/2))
print(result)

[[-0.6957507  -0.70093129]
 [-0.26271447 -0.35688905]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [17]:
A = np.random.uniform(0,10,10)

print (np.floor(A))       # np.floor() : 내림함수
print (np.ceil(A)-1)      # np.ceil() : 올림함수이므로, 1을 빼면 내림함수와 같은 효과
print (A.astype(int))     # array의 dtype을 정수로 변환
print (np.trunc(A))       # np.trunc() : 내림함수

[2. 7. 4. 7. 5. 9. 1. 1. 5. 5.]
[2. 7. 4. 7. 5. 9. 1. 1. 5. 5.]
[2 7 4 7 5 9 1 1 5 5]
[2. 7. 4. 7. 5. 9. 1. 1. 5. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [13]:
# My solution
A = np.ones((5,5))
A[0:5] = np.arange(0,5)
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [14]:
# Other solution
B = np.zeros((5,5))
B += np.arange(0,5)
print(B)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [27]:
# generator?

# yield?

# np.fromiter?

In [28]:
def generate():
  for x in range(10):
    yield x

A = np.fromiter(generate(), dtype=float, count=-1)
print(A)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [29]:
# np.linspace(start, stop, number of array's data, endpoint=True or False)
A = np.linspace(0,1,11, endpoint=False)[1:]     # [1:]을 붙이지 않으면 0이 포함되어 출력되므로, 2번째 데이터부터 출력되도록 설정
print(A)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


(10,)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [31]:
# My solution
A = np.random.random(10)
sorted(A)         # sorted() : 복사본을 정렬, 원본은 그대로 유지
print(A)          # A의 순서는 그대로 유지

[0.96109545 0.43908523 0.74659658 0.39671838 0.74860467 0.18233014
 0.59760737 0.28267914 0.601167   0.14383501]


In [36]:
# Other solution
B = np.random.random(10)
B.sort()        # array.sort() : array 자체를 정렬
print(B)        # B의 순서 변화

[0.11221493 0.17145109 0.21426    0.34841632 0.38785971 0.57141196
 0.59728034 0.71424159 0.79634746 0.84388625]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [37]:
# np.add.reduce(array, axis=0 or 1) : Reduces array's dimension by one, by applying ufunc along one axis.
A = np.arange(10)
np.add.reduce(A)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [41]:
A = np.random.randint(0,2,5)      # 0 이상 2 미만인 data 5개(5,)를 랜덤으로 출력
B = np.random.randint(0,2,5)      # 0 이상 2 미만은 data 5개(5,)를 랜덤으로 출력

# np.allclose(a,b) : a,b의 각 요소가 동일한지를 확인하는 함수
equal = np.allclose(A,B)
print(equal)

# np.array_equal(a,b) : a,b의 shape과 요소가 모두 동일한지를 확인하는 함수
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [38]:
A = np.random.random(10)
A.flags.writeable = False       # writeable = False : 데이터를 읽기 전용으로 설정
A[0] = 1                        # read-only로 설정되어 값을 변환하려 하면 error 발생

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing **`cartesian coordinates`**, convert them to **`polar coordinates`** (★★☆)

In [68]:
Z = np.random.random((10,2))        # random 10x2 matrix
X,Y = Z[:,0], Z[:,1]                # 1번째 칼럼 : x좌표, 2번째 칼럼 : y좌표

# convert cartesian coordinates --> polar coordinates
R = np.sqrt(X**2 + Y**2)            # r = sqrt(x^2 + y^2)
T = np.arctan2(Y,X)                 # np.arctan2(y좌표, x좌표) : 두 점 사이의 절대각도를 계산하는 함수

print(R, '\n')
print(T)

[0.67154717 0.65126715 0.46694466 0.53983022 0.4075567  0.58771925
 0.46446141 0.64542569 0.71521758 0.88058591] 

[1.39089981 1.26934216 0.22315542 0.72033424 0.77122563 0.07674092
 1.23283193 0.23017482 0.32756083 1.24478866]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [69]:
A = np.random.random(10)        # random vector (10,)
A[A.argmax()] = 0               # array.argmax() : 최대값을 갖는 data의 인덱스를 반환하는 함수
print(A)

[0.30229262 0.07167773 0.42662937 0.         0.73403666 0.52781597
 0.28951357 0.37690406 0.12860041 0.31110239]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [74]:
# np.meshgrid() : 1차원 좌표 배열에서 n차원 직사각형 격자를 만드는 함수 
A = np.zeros((5,5), [('x',float),('y',float)])    # custom dtype : (x,y) 좌표 형태로 출력
A['x'], A['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(A)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the **`Cauchy matrix`** C (**`Cij =1/(xi - yj)`**) (★★☆)

In [77]:
# np.subtract.outer?

In [79]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))               # np.linalg.det() : 행렬의 determinant 연산값을 반환하는 함수

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [80]:
# 1. scalar type : integer
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)                # np.iinfo() : int의 표현가능한 수의 한계를 반환
   print(np.iinfo(dtype).max)

# 2. scalar type : float
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)                # np.finfo() : float의 표현가능한 수의 한계를 반환 
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [105]:
np.set_printoptions(threshold=np.nan)
A = np.zeros((16,16))
print(A)

ValueError: ignored

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [81]:
A = np.arange(100)
a = np.random.uniform(0,100)
index = (np.abs(A-a)).argmin()
print(A[index])

18


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [82]:
A = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(A)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [83]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.06848752 0.24372566 0.38411262 0.2785484  0.41694858
  0.5161539  0.32996066 0.23979624 0.53820815]
 [0.06848752 0.         0.29386285 0.35493957 0.21122484 0.40580462
  0.44776083 0.2645948  0.20113956 0.48877144]
 [0.24372566 0.29386285 0.         0.62462795 0.45847955 0.64270057
  0.70891863 0.48951148 0.32121919 0.7806946 ]
 [0.38411262 0.35493957 0.62462795 0.         0.38648955 0.11537152
  0.44671182 0.4395666  0.51372833 0.21435139]
 [0.2785484  0.21122484 0.45847955 0.38648955 0.         0.48145937
  0.25047645 0.06125505 0.17838086 0.41970949]
 [0.41694858 0.40580462 0.64270057 0.11537152 0.48145937 0.
  0.56171054 0.53821469 0.58709107 0.30779112]
 [0.5161539  0.44776083 0.70891863 0.44671182 0.25047645 0.56171054
  0.         0.22778478 0.41155547 0.34742568]
 [0.32996066 0.2645948  0.48951148 0.4395666  0.06125505 0.53821469
  0.22778478 0.         0.18377076 0.45116753]
 [0.23979624 0.20113956 0.32121919 0.51372833 0.17838086 0.58709107
  0.41155547 0.18377

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [84]:
A = np.arange(10, dtype=np.float32)
A = A.astype(np.int32, copy=False)
print(A)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [85]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
A = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(A)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [89]:
A = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(A):
    print(index, value)
for index in np.ndindex(A.shape):
    print(index, A[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [90]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X + Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [91]:
n = 10
p = 3
A = np.zeros((n,n))
np.put(A, np.random.choice(range(n*n), p, replace=False),1)
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [92]:
A = np.random.rand(5, 10)

# Recent versions of numpy
B = A - A.mean(axis=1, keepdims=True)

# Older versions of numpy
B = A - A.mean(axis=1).reshape(-1, 1)

print(B)

[[ 0.15797533 -0.36214524  0.21688581 -0.0286641   0.25960724  0.2182287
  -0.30445024 -0.06856835 -0.17624723  0.08737809]
 [ 0.51158827 -0.27782225 -0.22692778  0.21404854 -0.38191301  0.11330722
   0.08136276 -0.02829126 -0.03437969  0.0290272 ]
 [ 0.07674163 -0.08255536 -0.38873213 -0.43188245  0.03053484 -0.23252435
   0.45646494  0.12890525  0.39781193  0.04523571]
 [-0.14373673 -0.27975585 -0.03138156  0.06192418 -0.41710593  0.08005591
   0.0326037   0.08954498  0.37679491  0.23105639]
 [-0.14115978  0.08645798 -0.13035718  0.23370244 -0.33186093  0.05908598
   0.44260707 -0.2828995   0.39036524 -0.32594132]]


#### 59. How to sort an array by the nth column? (★★☆)

In [93]:
A = np.random.randint(0,10,(3,3))
print(A)
print(A[A[:,1].argsort()])

[[8 3 7]
 [0 6 8]
 [1 7 5]]
[[8 3 7]
 [0 6 8]
 [1 7 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [94]:
A = np.random.randint(0,3,(3,10))
print((~A.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [96]:
A = np.random.uniform(0,1,10)
a = 0.5
m = A.flat[np.abs(A - a).argmin()]
print(m)

0.6134553206173734


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [97]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])

for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [98]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

A = NamedArray(np.arange(10), "range_10")
print(A.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [99]:
A = np.ones(10)
I = np.random.randint(0,len(A),20)
A += np.bincount(I, minlength=len(A))
print(A)

[5. 2. 4. 3. 1. 3. 2. 1. 4. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [101]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]

F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [102]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8
