<a href="https://colab.research.google.com/github/wldopie/ESAA/blob/main/HW_220401.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Chap 02. 사이킷런으로 시작하는 머신러닝**

## **01. 사이킷런 소개와 특징**
  - 사이킷런의 특징
    - 파이썬 기반의 다른 머신러닝 패키지도 사이킷런 스타일의 API를 지향할 정도로 쉽고 가장 파이썬스러운 API를 제공
    - 머신러닝을 위한 매우 다양한 알고리즘과 개발을 위한 편리한 프레임워크, API 제공
    - 오랜 기간 실전에서 검증되었으며, 매우 많은 환경에서 사용되는 성숙한 라이브러리

In [5]:
import sklearn
print(sklearn.__version__)

1.0.2


---

## **02. 첫 번째 머신러닝 만들어 보기 - 붓꽃 품종 예측하기**
  - 첫 번째 머신러닝 모델 : 붓꽃 데이터 세트를 활용해 붓꽃의 품종을 분류하고 예측
    - 붓꽃 데이터 세트 : 꽃잎의 길이와 너비, 꽃받침의 길이와 너비 feature를 기반으로 꽃의 품종을 예측하기 위함

  - 사이킷런 패키지의 3가지 모듈
    - `sklearn.datasets` : 사이킷런에서 자체적으로 제공하는 데이터 세트를 생성
    - `sklearn.tree` : 트리 기반 ML 알고리즘을 구현한 클래스의 모임
    - sklearn.model_selection : 데이터를 학습, 테스트용으로 분리하거나 최적의 하이퍼 파라미터를 평가하기 위한 모듈

In [6]:
# 사이킷런 패키지에서 사용할 3가지 모듈 임포트
from sklearn.datasets import load_iris                # dataset에서 iris 데이터를 로딩
from sklearn.tree import DecisionTreeClassifier       # 트리 기반의 ML 모형 사용
from sklearn.model_selection import train_test_split  # train data vs. test data를 나누는 함수

In [7]:
import pandas as pd

# 붓꽃 데이터 세트 로딩
iris = load_iris()

# iris.data는 Iris 데이터 세트에서 피처만으로 된 데이터를 numpy로 가지고 있음 (설명변수(X)로 구성)
iris_data = iris.data

# iris.target은 붓꽃 데이터 세트에서 레이블 데이터를 numpy로 가지고 있음 (반응변수(Y)로 구성)
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

# 붓꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 변환
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head()

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [8]:
# train data, test data 분리
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label,
                                                    test_size=0.2, random_state=11)     # random_state는 R에서의 set.seed와 동일한 역할

In [9]:
# 의사 결정 트리를 이용한 학습과 예측
# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

# 학습 수행
dt_clf.fit(X_train, y_train)

# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred = dt_clf.predict(X_test)

# 모델의 예측 성능 평가
# 정확도를 통해 확인, 정확도는 예측 결과가 실제 레이블 값과 얼마나 일치하는지를 평가
# accuracy_score(실제 y값, 예측값)
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9333


  - 붓꽃 데이터 세트로 분류를 예측한 프로세스
    
    
    1. 데이터 세트 분리 : 데이터를 train data, test data로 구분
    2. 모델 학습 : train data를 기반으로 ML 알고리즘을 적용해 모델을 학습
    3. 예측 수행 : 학습된 ML 모델을 이용해 test data의 분류를 예측
    4. 모델 평가 : 예측된 결과값과 test data의 실제 결과값을 비교해 ML 모델의 성능을 평가
  

---

## **03. 사이킷런의 기반 프레임워크 익히기**

### 1) Estimator 이해 및 fit( ), predict( ) 메서드
  - 모델 학습 : `fit()`, 모델 예측 : `predict()`
  - 분류 알고리즘 클래스 : Classifier, 회귀 알리즘 클래스 : Regressor
    - Classifier + Regresspr = Estimator
  

### 2) 사이킷런의 주요 모듈
    1. 예제 데이터
        - sklearn.datasets : 예제로 제공되는 데이터 세트

    2. 피처 처리
        - sklearn.preprocessing : 전처리에 필요한 가공 기능 제공
        - sklearn.feature_selection : 알고리즘에 큰 영향을 미치는 피처를 우선순위대로 셀렉션
        - sklearn.feature_extraction : 텍스트 데이터나 이미지 데이터의 벡터화된 피처를 추출하는 데 사용

    3. 피처 처리 & 차원 축소
        - sklearn.decomposition : 차원 축소와 관련한 알고리즘 지원

    4. 데이터 분리, 검증 & 파라미터 튜닝
        - sklearn.model_selection : 학습용/테스트용 분리, 최적 파라미터 추출 API 제공

    5. 평가
        - sklearn.metrics : 다양한 성능 측정 방법 제공
        
    6. ML 알고리즘
        - sklearn.ensemble : 앙상블 알고리즘 제공 (ex. 랜덤 포레스트, 그래디언트 부스팅 등)
        - sklearn.linear_model : 선형 회귀, 라쏘 및 로지스틱 회귀 관련 알고리즘 제공
        - sklearn.naive_bayes : 나이브 베이즈 알고리즘 제공
        - sklearn.neighbors : 최근접 이웃 알고리즘 제공 (ex. K-NN)
        - sklearn.svm : 서포트 벡터 머신 알고리즘 제공
        - sklearn.tree : 의사 결정 트리 알고리즘 제공
        - sklearn.cluster : 비지도 클러스터링 알고리즘 제공 (ex. k-평균, 계층형 등)

    7. 유틸리티
        - sklearn.pipeline : 피처 처리, 알고리즘 학습, 예측 등을 함께 묶어서 실행



### 3) 내장된 예제 데이터 세트
  - `datasets.load_boston()`, `datasets.load_breast_cancer()`, `datasets.load_diabetes()`, `datasets.load_digits()`, `datasets.load_iris()`
  - 해당 데이터 세트는 일반적으로 딕셔너리 형태
    - `data` : `피처`의 데이터 세트
    - `target` : `레이블` 데이터 세트
    - `target_names` : 개별 `레이블의 이름`
    - `feature_names` : `피처의 이름`
    - `DESCR` : 데이터 세트에 대한 설명과 각 피처의 설명

In [10]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))      # brunch 클래스 : 파이썬 딕셔너리 자료형과 유사

<class 'sklearn.utils.Bunch'>


In [11]:
keys = iris_data.keys()
print('붓꽃 데이터 세트의 키들:', keys)     # dict_keys의 형태로 출력
iris.data                                   # 데이터세트.key를 입력하면 해당 key 값들을 확인할 수 있음

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [12]:
# 1. feature_names 확인 (X)
print('\n feature_names의 type:', type(iris_data.feature_names))
print(' feature_names의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

# 2. target_names 확인 (Y)
print('\n target_names의 type:', type(iris_data.target_names))
print(' target_names의 shape:', len(iris_data.target_names))
print(iris_data.target_names)

# 3. data 확인 (X)
print('\n data의 type:', type(iris_data.data))
print(' data의 shape:', len(iris_data.data))
print(iris_data.data)

# 4. target 확인 (Y)
print('\n target의 type:', type(iris_data.target))
print(' target의 shape:', len(iris_data.target))
print(iris_data.target)


 feature_names의 type: <class 'list'>
 feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>
 target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
 data의 shape: 150
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.

---

## **04. Model Selection 모듈 소개**

### 1) 학습/테스트 데이터 세트 분리 - `train_test_split( )`
  - train_test_split(피처 데이터, 레이블 데이터)
    - test_size : 테스트 데이터의 비율을 설정 
    - shuffle : 데이터를 분리하기 전 미리 섞을지를 결정 
    - random_state : 호출할 때마다 동일한 학습/테스트용 데이터를 생성하기 위해 주어지는 난수 값

In [13]:
from sklearn.datasets import load_iris                
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data, train_label)

# 1. 학습 데이터로 예측 수행
pred = dt_clf.predict(train_data)
print(accuracy_score(train_label, pred))      # 학습한 데이터로 예측을 수행했으므로, 정확도는 1

1.0


In [14]:
from sklearn.datasets import load_iris                
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

dt_clf = DecisionTreeClassifier()
iris_data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target,
                                                    test_size=0.3, random_state=121)

# 모델 학습
dt_clf.fit(X_train, y_train)

# 모델 예측
pred = dt_clf.predict(X_test)
print(accuracy_score(y_test, pred))

0.9555555555555556


### 2) 교차 검증
  - 과적합 : 학습 데이터에만 과도하게 최적화되어, 다른 데이터로 실제 예측을 수행할 때 예측 성능이 과도하게 떨어지는 경우
  - 이를 방지하기 위해 교차 검증을 활용
    - 데이터 세트를 `학습, 검증, 테스트 데이터로 세분화`


1.   `K 폴드 교차 검증` : `KFold(n_splits = k)`
2.   `Stratified K 폴드` : `StratifiedKFold(n_splits = k)`



> **K 폴드 교차 검증**

In [15]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)       # 일정한 값으로 출력하기 위해 set.seed

# 5개의 폴드 세트로 분리하는 k-fold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150


In [16]:
n_iter = 0

# KFold 객체의 split()을 호출하면 폴드 별 학습용, 검증용 데이터의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features):
  
  # kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  
  # 학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)
  n_iter += 1
  
  # 반복 시마다 정확도 측정
  accuracy = np.round(accuracy_score(y_test, pred), 4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print('\n#{0} 교차 검증 정확도 : {1}, 학습 데이터 크기 : {2}, 검증 데이터 크기 : {3}'.format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

# 개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도 : 1.0, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 : 0.9667, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 : 0.8667, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 : 0.9333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 : 0.7333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
#5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9


> **Stratified K 폴드**
  - 불균형한 분포도를 가진 레이블 데이터 집합을 위한 K 폴드 방식
    - 불균형한 분포도? 특정 레이블 값이 특이하게 많거나 매우 적어서 분포가 치우치는 것
  - 레이블 데이터 집합이 원본 데이터 집합의 레이블 분포를 학습 및 테스트 세트에 제대로 분배하지 못하는 경우의 문제를 해결
  - 즉, 원본 데이터의 레이블 분포를 먼저 고려한 뒤, 분포와 동일하게 학습과 검증 데이터 세트를 분배

In [17]:
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [18]:
# kfold로 교차 검증
fold = KFold(n_splits=3)
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
  n_iter += 1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print('## 교차 검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n', label_train.value_counts())
  print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 1    50
2    50
0    20
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    30
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 2    50
1    40
0    30
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    20
1    10
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 0    50
2    50
1    20
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    30
Name: label, dtype: int64
## 교차 검증: 4
학습 레이블 데이터 분포:
 0    50
1    40
2    30
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    20
1    10
Name: label, dtype: int64
## 교차 검증: 5
학습 레이블 데이터 분포:
 0    50
1    50
2    20
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    30
Name: label, dtype: int64


In [19]:
# stratified k 폴드로 교차 검증
from sklearn.model_selection import StratifiedKFold


skf = StratifiedKFold(n_splits=3)
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
  n_iter += 1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print('## 교차 검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n', label_train.value_counts())
  print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
1    17
2    16
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
2    17
1    16
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    17
2    17
0    16
Name: label, dtype: int64


In [20]:
dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy = []

# StratifiedKFold의 split() 호출시 반드시 레이블 데이터 세트도 추가 입력 필요
for train_index, test_index in skfold.split(features, label):
  
  # split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  
  # 학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)

  # 반복 시마다 정확도 측정
  n_iter += 1
  accuracy = np.round(accuracy_score(y_test, pred), 4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print('\n#{0} 교차 검증 정확도 : {1}, 학습 데이터 크기 : {2}, 검증 데이터 크기 : {3}'.format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

# 교차 검증별 정확도 및 평균 정확도 계산
print('\n## 교차 검증별 정확도:', np.round(cv_accuracy, 4))
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도 : 0.98, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도 : 0.94, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도 : 0.98, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도: [0.98 0.94 0.98]

## 평균 검증 정확도: 0.9666666666666667


> 교차 검증을 보다 간편하게 - **cross_val_score( )**
  - `cross_val_score`(estimator, X, y, scoring, cv)
    - `estimator` : Classifier / Regressor
    - X : 피처 데이터
    - y : 레이블 데이터
    - `scoring` : 예측 성능을 평가하는 지표 (ex. accuracy)
    - `cv` : 교차 검증 폴드 수

In [21]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
label = iris_data.target

# 성능 지표는 정확도(accuracy), 교차 검증 세트는 3개
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print(np.round(scores, 4))            # 교차 검증별 정확도
print(np.round(np.mean(scores), 4))   # 평균 검증 정확도

[0.98 0.94 0.98]
0.9667


### 3) GridSearchCV - 교차 검증과 최적 하이퍼 파라미터 튜닝을 한 번에
  - `GridSearchCV` : 알고리즘에 사용되는 `하이퍼 파라미터를 순차적으로 입력`하면서 편리하게 `최적의 파라미터를 도출`

In [22]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

# 데이터를 로딩하고 학습 데이터와 테스트 데이터 분리
iris_data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target,
                                                    test_size=0.2, random_state=121)

dtree = DecisionTreeClassifier()

## 파라미터를 딕셔너리 형태로 설정
parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [23]:
import pandas as pd

# param_grid의 하이퍼 파라미터를 3개의 train, test set fold로 나누어 테스트 수행 설정
## refit = True가 default. True이면 가장 좋은 파라미터 설정으로 재학습
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

# 붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train, y_train)

# GridSearchCV 결과를 추출해 DataFrame으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 
           'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

  - `params` : 수행할 때마다 `적용된 개별 하이퍼 파라미터`값
  - `rank_test_score` : 하이퍼 파라미터별로 `성능이 좋은 score 순위`
  - `mean_test_score` : 개별 하이퍼 파라미터별로 `CV의 폴딩 테스트 세트`에 대해 `총 수행한 평가의 평균값`

In [24]:
print('GridSearchCV 최적 파라미터:', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도:{0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도:0.9750


In [25]:
# GridSearchCV의 refit으로 이미 학습된 estimator 반환
estimator = grid_dtree.best_estimator_          # 학습된 모델

# GridSearchCV의 best_estimator_는 이미 최적 학습이 됐으므로 별도 학습이 필요 없음
pred = estimator.predict(X_test)
print('테스트 데이터 세트 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

테스트 데이터 세트 정확도: 0.9667


---

## **05. 데이터 전처리**
  - 데이터 전처리는 ML 알고리즘만큼 중요
  - 결손값, 즉 `Null 값은 허용되지 않음`
    - 따라서 결손값은 `적당한 값으로 대체`해서 채워주어야 하며, `결측치가 너무 많은 경우 해당 칼럼을 제거`하는 것도 하나의 방법
    - 결손값을 채워 넣는 과정에서 `예측 왜곡이 일어날 수 있으므로 유의`해야 함
  - 사이킷런은 문자열 값을 입력 값으로 허용하지 않음
    - 모든 `문자열 값`은 인코딩되어 `숫자형으로 반환`

### 1) 데이터 인코딩

> **레이블 인코딩**
  - `카테고리 피처`를 코드형 `숫자 값으로` 변환
  - `LabelEncoder`를 객체로 생성, `fit()`과 `transform()`을 통해 레이블 인코딩 수행
  - 편리하게 문자열을 숫자형 카테고리로 변환할 수 있지만, `일괄적인 숫자 값`으로 변환되기 때문에 `예측 성능이 떨어질 수 있음`
    - 숫자 값의 경우, 특정 알고리즘에서 가중치가 부여될 가능성이 있음
    - 따라서 선형 회귀에는 적용하면 안됨

In [26]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 레이블 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [27]:
# 인코딩 클래스 확인
print('인코딩 클래스:', encoder.classes_)     # 왼쪽부터 순서대로 0, 1, ... , 5로 인코딩

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [28]:
# 인코딩된 값을 다시 디코딩
print('디코딩 원본값:', encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


> **One-Hot Encoding**
  - `고유 값`에 해당하는 칼럼에만 `1`, `나머지 칼럼`에는 `0`을 표시하는 방식

In [29]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# 1. 먼저 숫자 값으로 변환을 위해 LabelEncoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 2. 2차원 데이터로 변환
labels = labels.reshape(-1,1)       # 칼럼이 1인 2차원 데이터

# 3. One-Hot Encoding 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('One-Hot 인코딩 데이터')
print(oh_labels.toarray())
print('One-Hot 인코딩 데이터 차원')
print(oh_labels.shape)

One-Hot 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
One-Hot 인코딩 데이터 차원
(8, 6)


In [30]:
# 판다스의 API : get_dummies()
# 문자열 카테고리를 숫자형으로 변환하지 않아도 원-핫 인코딩이 가능
import pandas as pd

df = pd.DataFrame({'item' : ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

### 2) 피처 스케일링과 정규화
  - `피처 스케일링`
    - `표준화` : 개별 피처를 `평균이 0, 분산이 1인 값`으로 변환
    - `정규화` : 개별 데이터의 `크기를 모두 똑같은 단위`로 변경
  - 벡터 정규화
    - 선형대수 개념의 정규화

### 3) StandardScaler
  - `StandardScaler` : 개별 피처를 `평균이 0, 분산이 1인 값`으로 변환
  - 일반적인 의미의 `표준화` (가우시안 분포 가정)

In [31]:
from sklearn.datasets import load_iris
import pandas as pd

# 붓꽃 데이터 세트를 로딩하고 DataFrame으로 변환
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

print('feature들의 평균값')
print(iris_df.mean())
print('\n feature들의 분산값')
print(iris_df.var())

feature들의 평균값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

 feature들의 분산값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [32]:
from sklearn.preprocessing import StandardScaler

# StandardScaler 객체 생성
scaler = StandardScaler()

# StandardScaler로 데이터 세트 변환 / fit(), transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform() 시 스케일 변환된 데이터 세트가 Numpy ndarray로 반환, 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 평균값')
print(iris_df_scaled.mean())          # 평균이 0에 근사
print('\n feature들의 분산값')
print(iris_df_scaled.var())           # 분산이 1에 근사

feature들의 평균값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

 feature들의 분산값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


### 4) MinMaxScaler
  - `MinMaxScaler` : 데이터값을 `0과 1사이의 범위` 값으로 변환
  - 일반적인 의미의 `정규화` (가우시안 분포 가정 x)

In [33]:
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler 객체 생성
scaler = MinMaxScaler()

# MinMaxScaler로 데이터 세트 변환, fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

# transform() 시 스케일 변환된 데이터 세트가 Numpy ndarray로 반환돼 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print(iris_df_scaled.min())         # 최솟값 = 0
print(iris_df_scaled.max())         # 최댓값 = 1

sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


### 5) 학습 데이터와 테스트 데이터의 스케일링 변환 시 유의점
  - `Scaler 객체`를 이용해 `학습 데이터` 세트로 `fit()과 transform()을 적용`, `테스트 데이터` 세트로는 다시 fit()을 수행하지 않고 `학습 데이터 세트로 fit()을 수행한 결과를 이용`해 `transform() 변환`을 적용
  - 즉, `학습 데이터로 fit()이 적용`된 스케일링 기준 정보를 `그대로 테스트 데이터에 적용`해야 하며, 그렇지 않고 테스트 데이터로 `다시 새로운 스케일링 기준 정보`를 만들게 되면 `학습 데이터와 테스트 데이터의 스케일링 기준 정보가 달라져` 올바른 예측이 어려움
  

    1. 가능하다면 전체 데이터의 스케일링 변환을 먼저 적용한 뒤, 학습과 테스트 데이터로 분리
    2. 1이 여의치 않다면, 테스트 데이터 변환 시에는 fit()이나 fit_transform()을 적용하지 않고 학습 데이터로 이미 fit()된 Scaler 객체를 이용해 transform() 변환

In [34]:
# 1. 테스트 데이터에 fit()을 적용하는 경우
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# 학습 데이터는 0부터 10까지, 테스트 데이터는 0부터 5까지 값을 가지는 데이터 세트로 생성
# Scaler 클래스의 fit(), transform()은 2차원 이상 데이터만 가능하므로, reshape(-1,1)로 차원 변경
train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

# MinMaxSclaer 객체에 별도의 feature_range 파라미터 값을 지정하지 않으면 0~1 값으로 변환
scaler = MinMaxScaler()

# fit()하게 되면 train_array 데이터의 최솟값이 0, 최댓값이 10으로 설정
scaler.fit(train_array)

# 1/10 scale로 train_array 데이터 변환, 원본 10 -> 1로 변환
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터:', np.round(train_array.reshape(-1), 2))           # 1 ~ 10
print('Scale된 train_array 데이터:', np.round(train_scaled.reshape(-1), 2))       # 0.1 ~ 1

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [35]:
# MinMaxScaler에 test_array를 fit()하게 되면 원본 데이터의 최솟값이 0, 최댓값이 5로 설정
scaler.fit(test_array)

# 1/5 scale로 test_array 데이터 변환, 원본 5 -> 1로 변환
test_scaled = scaler.transform(test_array)

# test_array의 scale 변환 출력
print(np.round(test_array.reshape(-1), 2))        # 원본 : 0 ~ 5
print(np.round(test_scaled.reshape(-1), 2))       # 스케일링 : 0 ~ 1.0

[0 1 2 3 4 5]
[0.  0.2 0.4 0.6 0.8 1. ]


  - 위와 같이 `테스트 데이터`에 `fit()`을 적용할 경우, `학습 데이터와 스케일링이 맞지 않는 것`을 확인할 수 있다.
  - 따라서 `테스트 데이터`는 반드시 `학습 데이터의 스케일링 기준을 따라야` 하며, 테스트 데이터의 1 값은 학습 데이터와 동일하게 0.1 값으로 변환되어야 함
  - 그러므로 테스트 데이터에 fit()을 적용하지 않고 , `학습 데이터로 fit()이 적용된 Scaler 객체를 이용`해 `transform()`으로 변환

In [36]:
scaler = MinMaxScaler()
scaler.fit(train_array)     # train_array로 fit()
train_scaled = scaler.transform(train_array)
print(np.round(train_array.reshape(-1), 2))       # 원본 train_array = 0 ~ 10
print(np.round(train_scaled.reshape(-1), 2))      # 스케일링 train_array = 0.1 ~ 1

# test_array에 Scaler 변환을 할 때는 반드시 fit()을 호출하지 않고 transform()만으로 변환
test_scaled = scaler.transform(test_array)        # train_array로 fit한 결과를 사용
print(np.round(test_array.reshape(-1), 2))        # 원본 test_array = 0 ~ 5
print(np.round(test_scaled.reshape(-1), 2))       # 스케일링 test_array = 0 ~ 0.5

[ 0  1  2  3  4  5  6  7  8  9 10]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[0 1 2 3 4 5]
[0.  0.1 0.2 0.3 0.4 0.5]
